### ISSUE TITLE
Update Verilator to latest revision

### ISSUE THREAD

**Issue by howardtr** [chipsalliance/caliptra-rtl#79] opened 2023-05-03 22:40 UTC
There's a verilator bug that was found as part of debugging https://github.com/chipsalliance/caliptra-rtl/issues/71

At a high level, it looks like there are functional differences between the following lines of code in soc_ifc_top with verilator 5.002 -> 5.010.  This was seen working in 4.228: https://github.com/chipsalliance/caliptra-rtl/blob/main/src/soc_ifc/rtl/soc_ifc_top.sv#L685-L690

// Notworking
```
always_comb begin
  for (int i = 0; i < WDT_TIMEOUT_PERIOD_NUM_DWORDS; i++) begin
    timer1_timeout_period[i] = soc_ifc_reg_hwif_out.CPTRA_WDT_TIMER1_TIMEOUT_PERIOD[i].timer1_timeout_period.value;
    timer2_timeout_period[i] = soc_ifc_reg_hwif_out.CPTRA_WDT_TIMER2_TIMEOUT_PERIOD[i].timer2_timeout_period.value;
  end
end
```

// Working
```
for (genvar j = 0; j < WDT_TIMEOUT_PERIOD_NUM_DWORDS; j++) begin
  assign timer1_timeout_period_good[j] = soc_ifc_reg_hwif_out.CPTRA_WDT_TIMER1_TIMEOUT_PERIOD[j].timer1_timeout_period.value;
  assign timer2_timeout_period_good[j] = soc_ifc_reg_hwif_out.CPTRA_WDT_TIMER2_TIMEOUT_PERIOD[j].timer2_timeout_period.value;
end
```

Here's an image of the right side assignment being static, while the left assignment value is toggling (thanks @calebofearth for the image)
https://user-images.githubusercontent.com/11879229/235814411-6f690e79-d70f-4aa0-810e-d3dda6f21b1f.png

There was an attempt at reproducing a smaller test case [here](https://github.com/chipsalliance/caliptra-rtl/issues/71#issuecomment-1533835203), but it seems like there are other processes in the design that may be contributing to this behavior.

Initially filing a bug in caliptra-rtl to track updating the version in our repo, and also will be used as a place to reference when we file a bug in the verilator repo.

**Comment by mkurc-ant** [comment] 2023-05-04 13:23
Thanks for reporting that. Does the problem occur both in Verilator 5.002 and 5.010 ?

**Comment by howardtr** [comment] 2023-05-04 20:51
I tested against 5.002, 5.004, 5.006, and 5.010, which all exhibit the issue.   4.228 seems to be the last known working state.

**Comment by kbieganski** [comment] 2023-05-09 14:32
This seems to be caused by the `force`/`release` statements in `caliptra_top_tb_services.sv`. Commenting out [this part](https://github.com/chipsalliance/caliptra-rtl/blob/3e0d8ee319bafde45a734e4762efb1573196a92a/src/integration/tb/caliptra_top_tb_services.sv#L439-L452) restores the correct behavior.

I managed to reproduce it in a smaller test case:
```systemverilog
module t(input clk);
  initial begin
    $dumpfile("dump.vcd");
    $dumpvars;
  end

  logic [31:0] lhs1, lhs2, rhs;
  logic cond = 0;

  always_comb lhs1 = rhs;
  assign lhs2 = rhs;

  always @(posedge clk) rhs = '1;

  always @(negedge clk) begin
    if (!cond) begin
      release lhs1;
      release lhs2;
    end
  end
endmodule
```
Only the `release`s are actually needed, and both `always_comb` and `assign` have this problem.

![caliptra-bug-master](https://github.com/chipsalliance/caliptra-rtl/assets/9216518/f01abcaa-f9e1-495e-be47-1f7f7e9d456c)

Interestingly, the `always_comb` bug also appeared for me on v4.228. So it seems like an older bug that's made more visible in v5.

![caliptra-bug-4 228](https://github.com/chipsalliance/caliptra-rtl/assets/9216518/08fedc7a-fe8e-417d-b763-bdc19693274d)

Haven't found a fix yet.

**Comment by howardtr** [comment] 2023-05-09 16:31
@kbieganski  awesome!

**Comment by kbieganski** [comment] 2023-05-12 11:44
@howardtr This should be fixed on current Verilator `master` (https://github.com/verilator/verilator/pull/4192)

**Comment by howardtr** [comment] 2023-05-15 16:22
Awesome, thank you for the quick turnaround on the fix!

@calebofearth - for awareness

**Comment by bharatpillilli** [comment] 2023-06-21 19:23
@howardtr -- Close this?

**Comment by howardtr** [comment] 2023-06-21 22:38
We should be able to close this out soon.  I have a pending PR that will update verilator to 5.012, which includes the fixes for the force/release

**Closed** 2023-06-21 23:58 UTC
