### ISSUE TITLE
Failed to deassert the reset of uc using JTAG for HVM

### ISSUE THREAD

**Issue by blueblue0124** [chipsalliance/caliptra-rtl#523] opened 2024-05-28 09:15 UTC
According to the section "Provisioning IDevID during manufacturing" in the Caliptra Main Spec, one should be able to use JTAG to set the `CPTRA_DBG_MANUF_SERVICE_REG` and `CPTRA_DBG_MANUF_SERVICE_REG` in `soc_ifc` and deassert the reset of the `uc`. In our test, we failed to do so. We found that when `BootFSMBrk` is set to one and `Fuse_Done` is high, the `boot_fsm_ps` is stuck in the `BOOT_WAIT` state. Thus, `fw_update_rst_window` is tied to 1.

```verilog
always_comb fw_update_rst_window = boot_fsm_ps inside {BOOT_FW_RST, BOOT_WAIT};
```

The `fw_update_rst_window` signal further disables the gated clock used in the `dmi_jtag_to_core_sync` module. As a result `reg_en` and `reg_wr_en` enable signals are tied to zero  disables the JTAG access to the `soc_ifc`.

There is a mismatch between the spec and the code. Can you confirm if this is the design intent?

**Comment by Nitsirks** [comment] 2024-06-07 17:15
dmi_jtag_to_core_sync reset should be powergood, and not be impacted by fw_update_rst_window. 

fw_update_rst_window is used to force the ahb bus idle during uC resets to protect from metastability on the bus due to RDC.

I'm going to need some more information to try to reproduce this. 

You are in debug or manufacturing mode and reach BOOT_WAIT state, and powergood is asserted, and you are not able to access JTAG?

**Comment by blueblue0124** [comment] 2024-06-07 20:16
> You are in debug or manufacturing mode and reach BOOT_WAIT state, and powergood is asserted, and you are not able to access JTAG?
@Nitsirks Yes,  that is correct. Powergood is asserted. The reset of dmi_jtag_to_core_sync is released already, but the input clock to the synchronizer is gated and tied to ground.

**Comment by Nitsirks** [comment] 2024-06-07 21:07
I understand the issue now. Looking into how our JTAG validation missed this.

Is it possible for you to see if changing this line resolves the issue for you? In the mean time I'll validate this as well.

```
always_comb fw_update_rst_window = (boot_fsm_ps == BOOT_FW_RST) |
                                   ((boot_fsm_ps == BOOT_WAIT) & (wait_count != 0));
```

**Comment by blueblue0124** [comment] 2024-06-08 01:07
> Is it possible for you to see if changing this line resolves the issue for you? In the mean time I'll validate this as well.

The change to the code works

```
telnet 127.0.0.1 4444
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Open On-Chip Debugger
> riscv.tap.0 riscv dmi_read 0x60
0x0
> riscv.tap.0 riscv dmi_write 0x60 1
> riscv.tap.0 riscv dmi_read 0x60
0x1
> riscv.tap.0 riscv dmi_read 0x61
0x0
> riscv.tap.0 riscv dmi_write 0x61 1
> riscv.tap.0 riscv dmi_read 0x61
0x1
```

**Comment by bharatpillilli** [comment] 2024-06-19 20:54
an old RDC change introduced this bug...PR is done, regressions ran, will be released into 1.1 and 1.0.2

**Closed** 2024-06-21 16:08 UTC
Labels: bug
